# Generated by Django 4.0.6 on 2022-08-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_usuario_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tel',
        ),
        migrations.AlterField(
            model_name='codebook',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
