# Generated by Django 4.1.1 on 2022-09-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0005_rename_usuarioinfo_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='descripción',
            field=models.TextField(blank=True),
        ),
    ]
