# Generated by Django 4.0.6 on 2022-10-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0006_alter_task_descripción'),
    ]

    operations = [
        migrations.AddField(
            model_name='codebook',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='disponible'),
        ),
    ]
