# Generated by Django 4.0.6 on 2023-01-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0010_docente_emocional_fisica_ludica_mental_espiritual'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emocional',
        ),
        migrations.DeleteModel(
            name='Fisica',
        ),
        migrations.DeleteModel(
            name='Ludica',
        ),
        migrations.DeleteModel(
            name='Mental',
        ),
        migrations.RemoveField(
            model_name='espiritual',
            name='espiritual_17',
        ),
        migrations.RemoveField(
            model_name='espiritual',
            name='espiritual_30',
        ),
        migrations.RemoveField(
            model_name='espiritual',
            name='espiritual_33',
        ),
        migrations.RemoveField(
            model_name='espiritual',
            name='espiritual_39',
        ),
        migrations.RemoveField(
            model_name='espiritual',
            name='espiritual_4',
        ),
        migrations.RemoveField(
            model_name='espiritual',
            name='espiritual_49',
        ),
        migrations.RemoveField(
            model_name='espiritual',
            name='espiritual_56',
        ),
        migrations.RemoveField(
            model_name='espiritual',
            name='espiritual_60',
        ),
        migrations.RemoveField(
            model_name='espiritual',
            name='total',
        ),
        migrations.AddField(
            model_name='espiritual',
            name='ecologica',
            field=models.IntegerField(null=True, verbose_name='Espiritual'),
        ),
        migrations.AddField(
            model_name='espiritual',
            name='economica',
            field=models.IntegerField(null=True, verbose_name='Espiritual'),
        ),
        migrations.AddField(
            model_name='espiritual',
            name='emocional',
            field=models.IntegerField(null=True, verbose_name='Emocional'),
        ),
        migrations.AddField(
            model_name='espiritual',
            name='espiritual',
            field=models.IntegerField(null=True, verbose_name='Espiritual'),
        ),
        migrations.AddField(
            model_name='espiritual',
            name='familiar',
            field=models.IntegerField(null=True, verbose_name='Espiritual'),
        ),
        migrations.AddField(
            model_name='espiritual',
            name='fisica',
            field=models.IntegerField(null=True, verbose_name='Espiritual'),
        ),
        migrations.AddField(
            model_name='espiritual',
            name='laboral',
            field=models.IntegerField(null=True, verbose_name='Espiritual'),
        ),
        migrations.AddField(
            model_name='espiritual',
            name='ludica',
            field=models.IntegerField(null=True, verbose_name='Espiritual'),
        ),
        migrations.AddField(
            model_name='espiritual',
            name='mental',
            field=models.IntegerField(null=True, verbose_name='Mental'),
        ),
        migrations.AddField(
            model_name='espiritual',
            name='social',
            field=models.IntegerField(null=True, verbose_name='Espiritual'),
        ),
    ]
