# Generated by Django 4.0.6 on 2023-01-15 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libro', '0011_delete_emocional_delete_fisica_delete_ludica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espiritual', models.IntegerField(default=0, verbose_name='Espiritual')),
                ('fisica', models.IntegerField(default=0, verbose_name='Física')),
                ('mental', models.IntegerField(default=0, verbose_name='Mental')),
                ('emocional', models.IntegerField(default=0, verbose_name='Emocional')),
                ('ludica', models.IntegerField(default=0, verbose_name='Lúdica')),
                ('familiar', models.IntegerField(default=0, verbose_name='Familiar')),
                ('social', models.IntegerField(default=0, verbose_name='Social')),
                ('economica', models.IntegerField(default=0, verbose_name='Económica')),
                ('ecologica', models.IntegerField(default=0, verbose_name='Ecológica')),
                ('laboral', models.IntegerField(default=0, verbose_name='Laboral')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Espiritual',
        ),
    ]
