# Generated by Django 4.0.6 on 2023-01-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0012_cuestionario_delete_espiritual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionario',
            name='ecologica',
            field=models.CharField(default='0', max_length=3, verbose_name='Ecológica'),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='economica',
            field=models.CharField(default='0', max_length=3, verbose_name='Económica'),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='emocional',
            field=models.CharField(default='0', max_length=3, verbose_name='Emocional'),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='espiritual',
            field=models.CharField(default='0', max_length=3, verbose_name='Espiritual'),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='familiar',
            field=models.CharField(default='0', max_length=3, verbose_name='Familiar'),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='fisica',
            field=models.CharField(default='0', max_length=3, verbose_name='Física'),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='laboral',
            field=models.CharField(default='0', max_length=3, verbose_name='Laboral'),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='ludica',
            field=models.CharField(default='0', max_length=3, verbose_name='Lúdica'),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='mental',
            field=models.CharField(default='0', max_length=3, verbose_name='Mental'),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='social',
            field=models.CharField(default='0', max_length=3, verbose_name='Social'),
        ),
    ]
