# Generated by Django 4.0.6 on 2023-01-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0013_alter_cuestionario_ecologica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quien_soy_yo', models.CharField(max_length=100, null=True, verbose_name='¿Quien Soy Yo?')),
                ('en_que_soy_o_no_exitoso', models.CharField(max_length=100, null=True, verbose_name='¿En que soy o no exitoso?')),
                ('gente_cosas', models.CharField(max_length=100, null=True, verbose_name='¿Qué significan para mí las cosas y personas')),
            ],
        ),
    ]
