# Generated by Django 4.0.6 on 2023-01-21 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libro', '0015_userdata_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiensoy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('respuesta', models.CharField(max_length=300, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Userdata',
        ),
    ]
