# Generated by Django 4.0.6 on 2023-01-21 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0016_quiensoy_delete_userdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiensoy',
            old_name='id',
            new_name='Quiensoy_id',
        ),
    ]
